Update docker-run.sh
tuxgasy/docker-dolibarr pull request #29
Opened 2020-09-02 08:17 UTC by vipera7

https://github.com/tuxgasy/docker-dolibarr/issues/27

Update Dolibarr (NOT TESTED !)

2020-09-03 16:34 UTC, mathieupotier requested changes
Some changes suggested in order to stick on CodeStyle in file.

You have 3 cases in your loop to deal with
 - major === CURRENT_MAJOR_VERSION => migrate from CURRENT_MAJOR_VERSION to major +1
 - major === NEW_MAJOR_VERSION => migrate from major to NEW_MAJOR_VERSION
 - and others that migrate from major to major + 1

RC because seems missing the third case IMHO

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +  OldMajorVersion=(${INSTALLED_VERSION//./ })
```suggestion
  CURRENT_MAJOR_VERSION=$(echo ${INSTALLED_VERSION} | cut -d. -f1)
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +  NewMajorVersion=(${TARGET_VERSION//./ })
```suggestion
 NEW_MAJOR_VERSION=$(echo ${TARGET_VERSION} | cut -d. -f1)
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +  for i in `seq ${OldMajorVersion[0]} $NewMajorVersion`
```suggestion
  for major in `seq ${CURRENT_MAJOR_VERSION} ${NEW_MAJOR_VERSION}`
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +    if [[ "${OldMajorVersion[0]}" -eq "$i" ]]; then
```suggestion
    if [[ "${CURRENT_MAJOR_VERSION}" -eq "${major}" ]]; then
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php upgrade.php $INSTALLED_VERSION $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```suggestion
      php upgrade.php ${INSTALLED_VERSION} $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php upgrade2.php $INSTALLED_VERSION $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```suggestion
      php upgrade2.php ${INSTALLED_VERSION} $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php step5.php $INSTALLED_VERSION $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1
```suggestion
      php step5.php ${INSTALLED_VERSION} $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +    elif [[ $((i+1)) != $((NewMajorVersion+1)) ]]; then
```suggestion
    elif [[ $((major+1)) != $((NEW_MAJOR_VERSION+1)) ]]; then
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php upgrade.php ${i}.0.0 $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```suggestion
      php upgrade.php ${major}.0.0 $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php upgrade2.php ${i}.0.0 $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```suggestion
      php upgrade2.php ${major}.0.0 $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1 && \
```

2020-09-03 16:34 UTC, mathieupotier commented on docker-run.sh
> +      php step5.php ${i}.0.0 $((i+1)).0.0 >> /var/www/documents/migration_error.html 2>&1
```suggestion
      php step5.php ${major}.0.0 $((major+1)).0.0 >> /var/www/documents/migration_error.html 2>&1
```

2020-09-15 12:48 UTC, vipera7 commented
@mathieupotier Thanks for the reply, I'm sorry but I have no idea how to make changes :( First time doing a Pull requests on github

2020-09-15 16:35 UTC, mathieupotier commented
Solution 1 : Just push a commit in your branch `vipera7:patch-1` with the changes I suggested
Solution 2 : you can also click on `commit suggestion` for each messages in this thread, and after pull changes on your branch and chek if everything is OK (commit and push fix if necessary)

Once done, I can re-review and acknowledge it, after @tuxgasy will merge it if he's OK with it.

2020-09-16 07:13 UTC, vipera7 commented
@mathieupotier Thanks for help. I hope I did it right, here is the updated docker-run.sh : 

https://github.com/vipera7/docker-dolibarr/blob/master/docker-run.sh

2022-06-28 11:56 UTC, closed without merging